name: red_bus_crocos_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^8.0.0
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  easy_localization: ^3.0.5
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^1.1.6
  # flutter_widget_from_html: ^0.8.5
  freezed_annotation: ^2.4.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_maps_flutter: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  huawei_map: ^6.11.2+302
  injectable: ^2.4.1
  insta_image_viewer: ^1.0.4
  overlay_support: ^2.1.0
  restart_app: ^1.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  widget_to_marker: ^1.0.4

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Euclid
      fonts:
        - asset: assets/fonts/EuclidFlexLight.ttf
          weight: 300
        - asset: assets/fonts/EuclidFlexRegular.ttf
          weight: 400
        - asset: assets/fonts/EuclidFlexMedium.ttf
          weight: 500
        - asset: assets/fonts/EuclidFlexSemiBold.ttf
          weight: 600
        - asset: assets/fonts/EuclidFlexBold.ttf
          weight: 700
