// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMFsJcT_1zO7wAG7KN1RqeMLe3kbaVSnI',
    appId: '1:713085165445:web:dc3b8d8c3571efb1126eec',
    messagingSenderId: '713085165445',
    projectId: 'red-bus-crocos',
    authDomain: 'red-bus-crocos.firebaseapp.com',
    storageBucket: 'red-bus-crocos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADiCkR4qXTu8CAZEPEWw29Jj_0X7jQ1xA',
    appId: '1:713085165445:android:f6c72d99064e38a0126eec',
    messagingSenderId: '713085165445',
    projectId: 'red-bus-crocos',
    storageBucket: 'red-bus-crocos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_Jk2AihInZFErnu77xC6-lAQ55lqb60',
    appId: '1:713085165445:ios:f41a0c092e310328126eec',
    messagingSenderId: '713085165445',
    projectId: 'red-bus-crocos',
    storageBucket: 'red-bus-crocos.appspot.com',
    iosBundleId: 'com.example.redBusCrocosProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_Jk2AihInZFErnu77xC6-lAQ55lqb60',
    appId: '1:713085165445:ios:f41a0c092e310328126eec',
    messagingSenderId: '713085165445',
    projectId: 'red-bus-crocos',
    storageBucket: 'red-bus-crocos.appspot.com',
    iosBundleId: 'com.example.redBusCrocosProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMFsJcT_1zO7wAG7KN1RqeMLe3kbaVSnI',
    appId: '1:713085165445:web:970e6c7dc043898d126eec',
    messagingSenderId: '713085165445',
    projectId: 'red-bus-crocos',
    authDomain: 'red-bus-crocos.firebaseapp.com',
    storageBucket: 'red-bus-crocos.appspot.com',
  );
}
